insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE)
VALUES
(1000L,'USD','INR',66);
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE)
VALUES
(1001L,'EUR','INR',75);
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE)
VALUES
(1002L,'AUD','INR',25);
insert into CURRENCY_EXCHANGE(ID,CURRENCY_FROM,CURRENCY_TO,CONVERSION_MULTIPLE)
VALUES
(1003L,'CAD','INR',60);